### ISSUE TITLE
Non-ASCII tags cause errors

### ISSUE THREAD

**Issue by aleksejrs** [Glutanimate/anki-editor-tag-hotkeys#1]
Change a tag to toggle to "вв".
When trying to toggle it, an error occurs:

```
/home/user/Anki/addons/anki-editor-tag-hotkeys.py:13: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if toggledTag in currentTags:
Traceback (most recent call last):
  File "/home/user/Anki/addons/anki-editor-tag-hotkeys.py", line 30, in <lambda>
    lambda : toggleTag(editor, "вв"))
  File "/home/user/Anki/addons/anki-editor-tag-hotkeys.py", line 17, in toggleTag
    editor.tags.setText(" ".join(currentTags))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

* Anki 2.0.33
* Qt 4.8.7 PyQt 4.11.4
* Python 2.7.11

**Comment by aleksejrs** [comment]
Changing `"вв"` to `"вв".decode('utf-8')` appears to have fixed it.  Thanks to [this message from which I tried a random part](http://goobbe.com/issue/7311267/utf-8-encoding-problems-in-python-joining-utf-8-with-ascii-string-interpolation-).

**Comment by Glutanimate** [comment]
I merged the PR. Thanks a lot for your contribution!
